### ISSUE TITLE
Определить процесс добавления сайта.

### ISSUE THREAD

**Issue by iGilga** [SuperBugCompany/politrange.webapi#9]
Какой вариант выбрать?
При добавлении сайта происходит следующим образом:
1. Добавляет в таблице страниц ссылки  как имя хоста?
2. Добавляет в таблице страниц  ссылки как имя хоста + robots.txt?
3. Не добавляет в таблице страниц, оставлять краулере самостоятельно разбирать с ним?

**Comment by developermsv** [comment]
Добавляет в таблице страниц ссылки как имя хоста?

**Comment by iGilga** [comment]
Ок

**Comment by developermsv** [comment]
Да, хочу аргументировать, думаю, что вэб-сервис не должен ходить в инет по страницам - это чревато ошибками и подвисаниям, вэб-сервис должен, только отвечать на запросы из инета, а не порождать их в инет и ждать ответа.

**Comment by Kartavec** [comment]
> > Добавляет в таблице страниц ссылки как имя хоста?
> > Вот этот вариант мне нравится меньше всего. в таблице страниц - должны быть ссылки на страницы. Т.е.

http://lenta.ru
http://lenta.ru/robots.txt

и т.д.

Я бы выбрал вариант 3.
То что мы начинаем обход с robots.txt - это детали реализации краулера.

Вариант 2 тоже имеет право на существование.

**Comment by Kartavec** [comment]
> > Да, хочу аргументировать, думаю, что вэб-сервис не должен ходить в инет по страницам 

Веб-сервис и не пойдет в инет по страницам ни при одном из вариантов

**Comment by iGilga** [comment]
Хорошо, давай берем 3 вариант, но хотел бы чтоб у Константина какой-то код быть тут.
П.с. Задачку новую для него парсер ссылки с html с помощью Html Agility Pack?

**Comment by Kartavec** [comment]
А зачем нам парсер с Html Agiliy Pack? Что он должен делать?

**Comment by iGilga** [comment]
Бывает сайт без sitemap. Например rbk.ru. Должен с html парсить href и фильтровать ссылки на присутствии имя хоста в них.

**Comment by Kartavec** [comment]
Юрий, может в trello будем такие вещи вести? Чтоб была единая система тиктов.

> Например rbk.ru. Должен с html парсить href и фильтровать ссылки на присутствии имя хоста в них.

Да, согласен.

**Comment by developermsv** [comment]
Юр, так переносим в трелло?

**Comment by iGilga** [comment]
Нет, достаточно ссылка в трелло.

**Comment by developermsv** [comment]
Так сейчас, алгоритм отрабатывает в рамках, зачем расширять ?

**Comment by iGilga** [comment]
По второй версии веб-сервис работает по алгоритму второго варианта.

> 2 Добавляет в таблице страниц ссылки как имя хоста + robots.txt?
